site_name: 'FAB101'

#todo
#site_description: 'todo'
#remote_branch: if we use GH pages

nav:
    - Das Projekt: 'index.md'
    - Zum Buch: 'buch.md'
    - English Summary: 'english.md'
    - Die Partner: 'konsortium.md'
#   - Publikationen: 'publikationen.md'
#   - Presse: 'presse.md'
    - Kontakt: 'kontakt.md'
    - Fab:UNIverse 2019: 'fabuniverse.md'
    - Fab:UNIverse 2018: 'fabuniverse-2018.md'
    - FabLearn 2019: 'fablearn-2019.md'
    - Impressum: 'impressum.md'

markdown_extensions:
  - admonition
  - meta
  - toc:
      permalink: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark

theme: 
  name: material
  custom_dir: 'theme'
  logo: 'images/logo_fab101.png'
  palette:
    primary: 'grey'
    accent: 'orange'

extra_css:
#    - css/extra.css
    - css/footer.css
