site_name: 'FAB101'
repo_url: 'https://github.com/oliverstickel/fab101-docs/'
repo_name: 'GitHub'

#todo
#site_description: 'todo'
#remote_branch: if we use GH pages


pages:
    #- News: 'news.md'
    - FAB101: 'index.md'
    - Publikationen: 'publikationen.md'
    - Presse: 'presse.md'
    - Partner: 'partner.md'
    - Projekte: 'projekte.md'
    #- Support: 'support.md'
    - Kontakt: 'kontakt.md'
    - Impressum: 'impressum.md'

markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=true)
  - footnotes

#theme: 'material'
theme_dir: 'theme/material'

extra_css:
    - css/footer.css
    
    
extra:
  logo: 'images/logo.svg'
  palette:
    primary: 'grey'
    accent: 'orange'
  font:
#    text: 'Open Sans'
    code: 'Inconsolata'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/cscwsiegen'
    - type: 'facebook'
      link: 'http://facebook.com/fablabsiegen'
