site_name: 'FAB101'

#todo
#site_description: 'todo'
#remote_branch: if we use GH pages

pages:
    - Das Projekt: 'index.md'
    - Das Team: 'konsortium.md'
#   - Publikationen: 'publikationen.md'
#   - Presse: 'presse.md'
    - Kontakt: 'kontakt.md'
    - Fab:UNIverse 2019: 'fabuniverse.md'
    - Fab:UNIverse 2018: 'fabuniverse-2018.md'
    - Impressum: 'impressum.md'


markdown_extensions:
  - admonition
  - codehilite(linenums=true)
  - toc(permalink=true)
  - footnotes
  - fontawesome_markdown

theme_dir: 'theme/material'

extra_css:
    - css/extra.css
    - css/footer.css

extra:
  logo: 'images/logo_fab101.png'
  palette:
    primary: 'grey'
    accent: 'orange'
  font:
#    text: 'Open Sans'
    code: 'Inconsolata'
  social:
    - type: 'twitter'
      link: 'https://twitter.com/cscwsiegen'
    - type: 'facebook'
      link: 'http://facebook.com/fablabsiegen'
